# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def p002():
    
    sum = 0
    max_num = 4e6
    
    f1 = 1
    f2 = 2
    
    while f1 < max_num:        
        if f1 % 2 == 0:
            sum+= f1        
        f1, f2 = f2, f1+f2
    
    return sum
        
if __name__ == "__main__":
    
    sum = p002()
    print "sum: ", sum